/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type AddrsInitParameters struct {
	Addr *string `json:"addr,omitempty" tf:"addr,omitempty"`

	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type AddrsObservation struct {
	Addr *string `json:"addr,omitempty" tf:"addr,omitempty"`

	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type AddrsParameters struct {

	// +kubebuilder:validation:Optional
	Addr *string `json:"addr" tf:"addr,omitempty"`

	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`
}

type BeginInitParameters struct {
	Addr *string `json:"addr,omitempty" tf:"addr,omitempty"`

	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type BeginObservation struct {
	Addr *string `json:"addr,omitempty" tf:"addr,omitempty"`

	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type BeginParameters struct {

	// +kubebuilder:validation:Optional
	Addr *string `json:"addr" tf:"addr,omitempty"`

	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`
}

type ClientIPAddrGroupInitParameters struct {
	Addrs []AddrsInitParameters `json:"addrs,omitempty" tf:"addrs,omitempty"`

	Prefixes []PrefixesInitParameters `json:"prefixes,omitempty" tf:"prefixes,omitempty"`

	Ranges []RangesInitParameters `json:"ranges,omitempty" tf:"ranges,omitempty"`

	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ClientIPAddrGroupObservation struct {
	Addrs []AddrsObservation `json:"addrs,omitempty" tf:"addrs,omitempty"`

	Prefixes []PrefixesObservation `json:"prefixes,omitempty" tf:"prefixes,omitempty"`

	Ranges []RangesObservation `json:"ranges,omitempty" tf:"ranges,omitempty"`

	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ClientIPAddrGroupParameters struct {

	// +kubebuilder:validation:Optional
	Addrs []AddrsParameters `json:"addrs,omitempty" tf:"addrs,omitempty"`

	// +kubebuilder:validation:Optional
	Prefixes []PrefixesParameters `json:"prefixes,omitempty" tf:"prefixes,omitempty"`

	// +kubebuilder:validation:Optional
	Ranges []RangesParameters `json:"ranges,omitempty" tf:"ranges,omitempty"`

	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ConfigpbAttributesInitParameters struct {
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type ConfigpbAttributesObservation struct {
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type ConfigpbAttributesParameters struct {

	// +kubebuilder:validation:Optional
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type DNSConfigsInitParameters struct {

	// Name for the gslb object. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	DomainName *string `json:"domainName,omitempty" tf:"domain_name,omitempty"`
}

type DNSConfigsObservation struct {

	// Name for the gslb object. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	DomainName *string `json:"domainName,omitempty" tf:"domain_name,omitempty"`
}

type DNSConfigsParameters struct {

	// Name for the gslb object. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	// +kubebuilder:validation:Optional
	DomainName *string `json:"domainName" tf:"domain_name,omitempty"`
}

type DNSVsesInitParameters struct {

	// Uuid of the gslb object. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	DNSVsUUID *string `json:"dnsVsUuid,omitempty" tf:"dns_vs_uuid,omitempty"`

	DomainNames []*string `json:"domainNames,omitempty" tf:"domain_names,omitempty"`
}

type DNSVsesObservation struct {

	// Uuid of the gslb object. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	DNSVsUUID *string `json:"dnsVsUuid,omitempty" tf:"dns_vs_uuid,omitempty"`

	DomainNames []*string `json:"domainNames,omitempty" tf:"domain_names,omitempty"`
}

type DNSVsesParameters struct {

	// Uuid of the gslb object. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	// +kubebuilder:validation:Optional
	DNSVsUUID *string `json:"dnsVsUuid" tf:"dns_vs_uuid,omitempty"`

	// +kubebuilder:validation:Optional
	DomainNames []*string `json:"domainNames,omitempty" tf:"domain_names,omitempty"`
}

type EndInitParameters struct {
	Addr *string `json:"addr,omitempty" tf:"addr,omitempty"`

	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type EndObservation struct {
	Addr *string `json:"addr,omitempty" tf:"addr,omitempty"`

	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type EndParameters struct {

	// +kubebuilder:validation:Optional
	Addr *string `json:"addr" tf:"addr,omitempty"`

	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`
}

type GSLBInitParameters struct {

	// Frequency with which messages are propagated to vs mgr. Value of 0 disables async behavior and rpc are sent inline. Allowed values are 0-5. Field introduced in 18.2.3. Unit is sec. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	AsyncInterval *string `json:"asyncInterval,omitempty" tf:"async_interval,omitempty"`

	// Max retries after which the remote site is treated as a fresh start. In fresh start all the configs are downloaded. Allowed values are 1-1024. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	ClearOnMaxRetries *string `json:"clearOnMaxRetries,omitempty" tf:"clear_on_max_retries,omitempty"`

	// Group to specify if the client ip addresses are public or private. Field introduced in 17.1.2. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	ClientIPAddrGroup []ClientIPAddrGroupInitParameters `json:"clientIpAddrGroup,omitempty" tf:"client_ip_addr_group,omitempty"`

	// Protobuf versioning for config pbs. Field introduced in 21.1.1. Allowed in enterprise edition with any value, essentials edition with any value, basic edition with any value, enterprise with cloud services edition.
	ConfigpbAttributes []ConfigpbAttributesInitParameters `json:"configpbAttributes,omitempty" tf:"configpb_attributes,omitempty"`

	// Sub domain configuration for the gslb. Gslb service's fqdn must be a match one of these subdomains. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	DNSConfigs []DNSConfigsInitParameters `json:"dnsConfigs,omitempty" tf:"dns_configs,omitempty"`

	// Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Allows enable/disable of gslbservice pool groups and pool members from the gslb follower members. Field introduced in 20.1.5. Allowed in enterprise edition with any value, enterprise with cloud services edition.
	EnableConfigByMembers *string `json:"enableConfigByMembers,omitempty" tf:"enable_config_by_members,omitempty"`

	// Frequency with which errored messages are resynced to follower sites. Value of 0 disables resync behavior. Allowed values are 60-3600. Special values are 0 - disable. Field introduced in 18.2.3. Unit is sec. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	ErrorResyncInterval *string `json:"errorResyncInterval,omitempty" tf:"error_resync_interval,omitempty"`

	// This is the max number of file versions that will be retained for a file referenced by the federated fileobject. Subsequent uploads of file will result in the file rotation of the older version and the latest version retained. Example  when a file upload is done for the first time, there will be a v1 version. Subsequent uploads will get mapped to v1, v2 and v3 versions. On the fourth upload of the file, the v1 will be file rotated and v2, v3 and v4 will be retained. Allowed values are 1-5. Field introduced in 30.2.1. Allowed in enterprise edition with any value, enterprise with cloud services edition.
	FileobjectMaxFileVersions *string `json:"fileobjectMaxFileVersions,omitempty" tf:"fileobject_max_file_versions,omitempty"`

	// This field indicates that this object is replicated across gslb federation. Field introduced in 17.1.3. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	IsFederated *string `json:"isFederated,omitempty" tf:"is_federated,omitempty"`

	// Mark this site as leader of gslb configuration. This site is the one among the avi sites. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	LeaderClusterUUID *string `json:"leaderClusterUuid,omitempty" tf:"leader_cluster_uuid,omitempty"`

	// This field disables the configuration operations on the leader for all federated objects. Cud operations on gslb, gslbservice, gslbgeodbprofile and other federated objects will be rejected. The rest-api disabling helps in upgrade scenarios where we don't want configuration sync operations to the gslb member when the member is being upgraded. This configuration programmatically blocks the leader from accepting new gslb configuration when member sites are undergoing upgrade. Field introduced in 17.2.1. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	MaintenanceMode *string `json:"maintenanceMode,omitempty" tf:"maintenance_mode,omitempty"`

	// Name for the gslb object. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Policy for replicating configuration to the active follower sites. Field introduced in 20.1.1. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	ReplicationPolicy []ReplicationPolicyInitParameters `json:"replicationPolicy,omitempty" tf:"replication_policy,omitempty"`

	// Frequency with which group members communicate. Allowed values are 1-3600. Unit is sec. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	SendInterval *string `json:"sendInterval,omitempty" tf:"send_interval,omitempty"`

	// The user can specify a send-interval while entering maintenance mode. The validity of this 'maintenance send-interval' is only during maintenance mode. When the user leaves maintenance mode, the original send-interval is reinstated. This internal variable is used to store the original send-interval. Field introduced in 18.2.3. Unit is sec. Allowed in enterprise edition with any value, essentials edition with any value, basic edition with any value, enterprise with cloud services edition.
	SendIntervalPriorToMaintenanceMode *string `json:"sendIntervalPriorToMaintenanceMode,omitempty" tf:"send_interval_prior_to_maintenance_mode,omitempty"`

	// Select avi site member belonging to this gslb. Minimum of 1 items required. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	Sites []SitesInitParameters `json:"sites,omitempty" tf:"sites,omitempty"`

	// It is a reference to an object of type tenant. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	TenantRef *string `json:"tenantRef,omitempty" tf:"tenant_ref,omitempty"`

	// This field indicates tenant visibility for gs pool member selection across the gslb federated objects.tenant scope can be set only during the gslb create and cannot be changed once it is set. Field introduced in 18.2.12,20.1.4. Allowed in enterprise edition with any value, enterprise with cloud services edition.
	TenantScoped *string `json:"tenantScoped,omitempty" tf:"tenant_scoped,omitempty"`

	// Third party site member belonging to this gslb. Field introduced in 17.1.1. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	ThirdPartySites []ThirdPartySitesInitParameters `json:"thirdPartySites,omitempty" tf:"third_party_sites,omitempty"`

	// Uuid of the gslb object. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`

	// The view-id is used in change-leader mode to differentiate partitioned groups while they have the same gslb namespace. Each partitioned group will be able to operate independently by using the view-id. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	ViewID *string `json:"viewId,omitempty" tf:"view_id,omitempty"`
}

type GSLBObservation struct {

	// Frequency with which messages are propagated to vs mgr. Value of 0 disables async behavior and rpc are sent inline. Allowed values are 0-5. Field introduced in 18.2.3. Unit is sec. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	AsyncInterval *string `json:"asyncInterval,omitempty" tf:"async_interval,omitempty"`

	// Max retries after which the remote site is treated as a fresh start. In fresh start all the configs are downloaded. Allowed values are 1-1024. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	ClearOnMaxRetries *string `json:"clearOnMaxRetries,omitempty" tf:"clear_on_max_retries,omitempty"`

	// Group to specify if the client ip addresses are public or private. Field introduced in 17.1.2. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	ClientIPAddrGroup []ClientIPAddrGroupObservation `json:"clientIpAddrGroup,omitempty" tf:"client_ip_addr_group,omitempty"`

	// Protobuf versioning for config pbs. Field introduced in 21.1.1. Allowed in enterprise edition with any value, essentials edition with any value, basic edition with any value, enterprise with cloud services edition.
	ConfigpbAttributes []ConfigpbAttributesObservation `json:"configpbAttributes,omitempty" tf:"configpb_attributes,omitempty"`

	// Sub domain configuration for the gslb. Gslb service's fqdn must be a match one of these subdomains. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	DNSConfigs []DNSConfigsObservation `json:"dnsConfigs,omitempty" tf:"dns_configs,omitempty"`

	// Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Allows enable/disable of gslbservice pool groups and pool members from the gslb follower members. Field introduced in 20.1.5. Allowed in enterprise edition with any value, enterprise with cloud services edition.
	EnableConfigByMembers *string `json:"enableConfigByMembers,omitempty" tf:"enable_config_by_members,omitempty"`

	// Frequency with which errored messages are resynced to follower sites. Value of 0 disables resync behavior. Allowed values are 60-3600. Special values are 0 - disable. Field introduced in 18.2.3. Unit is sec. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	ErrorResyncInterval *string `json:"errorResyncInterval,omitempty" tf:"error_resync_interval,omitempty"`

	// This is the max number of file versions that will be retained for a file referenced by the federated fileobject. Subsequent uploads of file will result in the file rotation of the older version and the latest version retained. Example  when a file upload is done for the first time, there will be a v1 version. Subsequent uploads will get mapped to v1, v2 and v3 versions. On the fourth upload of the file, the v1 will be file rotated and v2, v3 and v4 will be retained. Allowed values are 1-5. Field introduced in 30.2.1. Allowed in enterprise edition with any value, enterprise with cloud services edition.
	FileobjectMaxFileVersions *string `json:"fileobjectMaxFileVersions,omitempty" tf:"fileobject_max_file_versions,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// This field indicates that this object is replicated across gslb federation. Field introduced in 17.1.3. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	IsFederated *string `json:"isFederated,omitempty" tf:"is_federated,omitempty"`

	// Mark this site as leader of gslb configuration. This site is the one among the avi sites. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	LeaderClusterUUID *string `json:"leaderClusterUuid,omitempty" tf:"leader_cluster_uuid,omitempty"`

	// This field disables the configuration operations on the leader for all federated objects. Cud operations on gslb, gslbservice, gslbgeodbprofile and other federated objects will be rejected. The rest-api disabling helps in upgrade scenarios where we don't want configuration sync operations to the gslb member when the member is being upgraded. This configuration programmatically blocks the leader from accepting new gslb configuration when member sites are undergoing upgrade. Field introduced in 17.2.1. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	MaintenanceMode *string `json:"maintenanceMode,omitempty" tf:"maintenance_mode,omitempty"`

	// Name for the gslb object. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Policy for replicating configuration to the active follower sites. Field introduced in 20.1.1. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	ReplicationPolicy []ReplicationPolicyObservation `json:"replicationPolicy,omitempty" tf:"replication_policy,omitempty"`

	// Frequency with which group members communicate. Allowed values are 1-3600. Unit is sec. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	SendInterval *string `json:"sendInterval,omitempty" tf:"send_interval,omitempty"`

	// The user can specify a send-interval while entering maintenance mode. The validity of this 'maintenance send-interval' is only during maintenance mode. When the user leaves maintenance mode, the original send-interval is reinstated. This internal variable is used to store the original send-interval. Field introduced in 18.2.3. Unit is sec. Allowed in enterprise edition with any value, essentials edition with any value, basic edition with any value, enterprise with cloud services edition.
	SendIntervalPriorToMaintenanceMode *string `json:"sendIntervalPriorToMaintenanceMode,omitempty" tf:"send_interval_prior_to_maintenance_mode,omitempty"`

	// Select avi site member belonging to this gslb. Minimum of 1 items required. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	Sites []SitesObservation `json:"sites,omitempty" tf:"sites,omitempty"`

	// It is a reference to an object of type tenant. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	TenantRef *string `json:"tenantRef,omitempty" tf:"tenant_ref,omitempty"`

	// This field indicates tenant visibility for gs pool member selection across the gslb federated objects.tenant scope can be set only during the gslb create and cannot be changed once it is set. Field introduced in 18.2.12,20.1.4. Allowed in enterprise edition with any value, enterprise with cloud services edition.
	TenantScoped *string `json:"tenantScoped,omitempty" tf:"tenant_scoped,omitempty"`

	// Third party site member belonging to this gslb. Field introduced in 17.1.1. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	ThirdPartySites []ThirdPartySitesObservation `json:"thirdPartySites,omitempty" tf:"third_party_sites,omitempty"`

	// Uuid of the gslb object. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`

	// The view-id is used in change-leader mode to differentiate partitioned groups while they have the same gslb namespace. Each partitioned group will be able to operate independently by using the view-id. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	ViewID *string `json:"viewId,omitempty" tf:"view_id,omitempty"`
}

type GSLBParameters struct {

	// Frequency with which messages are propagated to vs mgr. Value of 0 disables async behavior and rpc are sent inline. Allowed values are 0-5. Field introduced in 18.2.3. Unit is sec. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	// +kubebuilder:validation:Optional
	AsyncInterval *string `json:"asyncInterval,omitempty" tf:"async_interval,omitempty"`

	// Max retries after which the remote site is treated as a fresh start. In fresh start all the configs are downloaded. Allowed values are 1-1024. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	// +kubebuilder:validation:Optional
	ClearOnMaxRetries *string `json:"clearOnMaxRetries,omitempty" tf:"clear_on_max_retries,omitempty"`

	// Group to specify if the client ip addresses are public or private. Field introduced in 17.1.2. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	// +kubebuilder:validation:Optional
	ClientIPAddrGroup []ClientIPAddrGroupParameters `json:"clientIpAddrGroup,omitempty" tf:"client_ip_addr_group,omitempty"`

	// Protobuf versioning for config pbs. Field introduced in 21.1.1. Allowed in enterprise edition with any value, essentials edition with any value, basic edition with any value, enterprise with cloud services edition.
	// +kubebuilder:validation:Optional
	ConfigpbAttributes []ConfigpbAttributesParameters `json:"configpbAttributes,omitempty" tf:"configpb_attributes,omitempty"`

	// Sub domain configuration for the gslb. Gslb service's fqdn must be a match one of these subdomains. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	// +kubebuilder:validation:Optional
	DNSConfigs []DNSConfigsParameters `json:"dnsConfigs,omitempty" tf:"dns_configs,omitempty"`

	// Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Allows enable/disable of gslbservice pool groups and pool members from the gslb follower members. Field introduced in 20.1.5. Allowed in enterprise edition with any value, enterprise with cloud services edition.
	// +kubebuilder:validation:Optional
	EnableConfigByMembers *string `json:"enableConfigByMembers,omitempty" tf:"enable_config_by_members,omitempty"`

	// Frequency with which errored messages are resynced to follower sites. Value of 0 disables resync behavior. Allowed values are 60-3600. Special values are 0 - disable. Field introduced in 18.2.3. Unit is sec. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	// +kubebuilder:validation:Optional
	ErrorResyncInterval *string `json:"errorResyncInterval,omitempty" tf:"error_resync_interval,omitempty"`

	// This is the max number of file versions that will be retained for a file referenced by the federated fileobject. Subsequent uploads of file will result in the file rotation of the older version and the latest version retained. Example  when a file upload is done for the first time, there will be a v1 version. Subsequent uploads will get mapped to v1, v2 and v3 versions. On the fourth upload of the file, the v1 will be file rotated and v2, v3 and v4 will be retained. Allowed values are 1-5. Field introduced in 30.2.1. Allowed in enterprise edition with any value, enterprise with cloud services edition.
	// +kubebuilder:validation:Optional
	FileobjectMaxFileVersions *string `json:"fileobjectMaxFileVersions,omitempty" tf:"fileobject_max_file_versions,omitempty"`

	// This field indicates that this object is replicated across gslb federation. Field introduced in 17.1.3. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	// +kubebuilder:validation:Optional
	IsFederated *string `json:"isFederated,omitempty" tf:"is_federated,omitempty"`

	// Mark this site as leader of gslb configuration. This site is the one among the avi sites. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	// +kubebuilder:validation:Optional
	LeaderClusterUUID *string `json:"leaderClusterUuid,omitempty" tf:"leader_cluster_uuid,omitempty"`

	// This field disables the configuration operations on the leader for all federated objects. Cud operations on gslb, gslbservice, gslbgeodbprofile and other federated objects will be rejected. The rest-api disabling helps in upgrade scenarios where we don't want configuration sync operations to the gslb member when the member is being upgraded. This configuration programmatically blocks the leader from accepting new gslb configuration when member sites are undergoing upgrade. Field introduced in 17.2.1. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	// +kubebuilder:validation:Optional
	MaintenanceMode *string `json:"maintenanceMode,omitempty" tf:"maintenance_mode,omitempty"`

	// Name for the gslb object. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Policy for replicating configuration to the active follower sites. Field introduced in 20.1.1. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	// +kubebuilder:validation:Optional
	ReplicationPolicy []ReplicationPolicyParameters `json:"replicationPolicy,omitempty" tf:"replication_policy,omitempty"`

	// Frequency with which group members communicate. Allowed values are 1-3600. Unit is sec. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	// +kubebuilder:validation:Optional
	SendInterval *string `json:"sendInterval,omitempty" tf:"send_interval,omitempty"`

	// The user can specify a send-interval while entering maintenance mode. The validity of this 'maintenance send-interval' is only during maintenance mode. When the user leaves maintenance mode, the original send-interval is reinstated. This internal variable is used to store the original send-interval. Field introduced in 18.2.3. Unit is sec. Allowed in enterprise edition with any value, essentials edition with any value, basic edition with any value, enterprise with cloud services edition.
	// +kubebuilder:validation:Optional
	SendIntervalPriorToMaintenanceMode *string `json:"sendIntervalPriorToMaintenanceMode,omitempty" tf:"send_interval_prior_to_maintenance_mode,omitempty"`

	// Select avi site member belonging to this gslb. Minimum of 1 items required. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	// +kubebuilder:validation:Optional
	Sites []SitesParameters `json:"sites,omitempty" tf:"sites,omitempty"`

	// It is a reference to an object of type tenant. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	// +kubebuilder:validation:Optional
	TenantRef *string `json:"tenantRef,omitempty" tf:"tenant_ref,omitempty"`

	// This field indicates tenant visibility for gs pool member selection across the gslb federated objects.tenant scope can be set only during the gslb create and cannot be changed once it is set. Field introduced in 18.2.12,20.1.4. Allowed in enterprise edition with any value, enterprise with cloud services edition.
	// +kubebuilder:validation:Optional
	TenantScoped *string `json:"tenantScoped,omitempty" tf:"tenant_scoped,omitempty"`

	// Third party site member belonging to this gslb. Field introduced in 17.1.1. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	// +kubebuilder:validation:Optional
	ThirdPartySites []ThirdPartySitesParameters `json:"thirdPartySites,omitempty" tf:"third_party_sites,omitempty"`

	// Uuid of the gslb object. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	// +kubebuilder:validation:Optional
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`

	// The view-id is used in change-leader mode to differentiate partitioned groups while they have the same gslb namespace. Each partitioned group will be able to operate independently by using the view-id. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	// +kubebuilder:validation:Optional
	ViewID *string `json:"viewId,omitempty" tf:"view_id,omitempty"`
}

type HmProxiesInitParameters struct {
	ProxyType *string `json:"proxyType,omitempty" tf:"proxy_type,omitempty"`

	// Uuid of the gslb object. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	SiteUUID *string `json:"siteUuid,omitempty" tf:"site_uuid,omitempty"`
}

type HmProxiesObservation struct {
	ProxyType *string `json:"proxyType,omitempty" tf:"proxy_type,omitempty"`

	// Uuid of the gslb object. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	SiteUUID *string `json:"siteUuid,omitempty" tf:"site_uuid,omitempty"`
}

type HmProxiesParameters struct {

	// +kubebuilder:validation:Optional
	ProxyType *string `json:"proxyType,omitempty" tf:"proxy_type,omitempty"`

	// Uuid of the gslb object. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	// +kubebuilder:validation:Optional
	SiteUUID *string `json:"siteUuid,omitempty" tf:"site_uuid,omitempty"`
}

type IPAddrInitParameters struct {
	Addr *string `json:"addr,omitempty" tf:"addr,omitempty"`

	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type IPAddrObservation struct {
	Addr *string `json:"addr,omitempty" tf:"addr,omitempty"`

	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type IPAddrParameters struct {

	// +kubebuilder:validation:Optional
	Addr *string `json:"addr" tf:"addr,omitempty"`

	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`
}

type IPAddressesInitParameters struct {
	Addr *string `json:"addr,omitempty" tf:"addr,omitempty"`

	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type IPAddressesObservation struct {
	Addr *string `json:"addr,omitempty" tf:"addr,omitempty"`

	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type IPAddressesParameters struct {

	// +kubebuilder:validation:Optional
	Addr *string `json:"addr" tf:"addr,omitempty"`

	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`
}

type LocationInitParameters struct {
	Location []LocationLocationInitParameters `json:"location,omitempty" tf:"location,omitempty"`

	Source *string `json:"source,omitempty" tf:"source,omitempty"`
}

type LocationLocationInitParameters struct {
	Latitude *string `json:"latitude,omitempty" tf:"latitude,omitempty"`

	Longitude *string `json:"longitude,omitempty" tf:"longitude,omitempty"`

	// Name for the gslb object. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	Tag *string `json:"tag,omitempty" tf:"tag,omitempty"`
}

type LocationLocationObservation struct {
	Latitude *string `json:"latitude,omitempty" tf:"latitude,omitempty"`

	Longitude *string `json:"longitude,omitempty" tf:"longitude,omitempty"`

	// Name for the gslb object. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	Tag *string `json:"tag,omitempty" tf:"tag,omitempty"`
}

type LocationLocationParameters struct {

	// +kubebuilder:validation:Optional
	Latitude *string `json:"latitude,omitempty" tf:"latitude,omitempty"`

	// +kubebuilder:validation:Optional
	Longitude *string `json:"longitude,omitempty" tf:"longitude,omitempty"`

	// Name for the gslb object. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// +kubebuilder:validation:Optional
	Tag *string `json:"tag,omitempty" tf:"tag,omitempty"`
}

type LocationObservation struct {
	Location []LocationLocationObservation `json:"location,omitempty" tf:"location,omitempty"`

	Source *string `json:"source,omitempty" tf:"source,omitempty"`
}

type LocationParameters struct {

	// +kubebuilder:validation:Optional
	Location []LocationLocationParameters `json:"location,omitempty" tf:"location,omitempty"`

	// +kubebuilder:validation:Optional
	Source *string `json:"source" tf:"source,omitempty"`
}

type PrefixesInitParameters struct {
	IPAddr []IPAddrInitParameters `json:"ipAddr,omitempty" tf:"ip_addr,omitempty"`

	Mask *string `json:"mask,omitempty" tf:"mask,omitempty"`
}

type PrefixesObservation struct {
	IPAddr []IPAddrObservation `json:"ipAddr,omitempty" tf:"ip_addr,omitempty"`

	Mask *string `json:"mask,omitempty" tf:"mask,omitempty"`
}

type PrefixesParameters struct {

	// +kubebuilder:validation:Optional
	IPAddr []IPAddrParameters `json:"ipAddr" tf:"ip_addr,omitempty"`

	// +kubebuilder:validation:Optional
	Mask *string `json:"mask" tf:"mask,omitempty"`
}

type RangesInitParameters struct {
	Begin []BeginInitParameters `json:"begin,omitempty" tf:"begin,omitempty"`

	End []EndInitParameters `json:"end,omitempty" tf:"end,omitempty"`
}

type RangesObservation struct {
	Begin []BeginObservation `json:"begin,omitempty" tf:"begin,omitempty"`

	End []EndObservation `json:"end,omitempty" tf:"end,omitempty"`
}

type RangesParameters struct {

	// +kubebuilder:validation:Optional
	Begin []BeginParameters `json:"begin" tf:"begin,omitempty"`

	// +kubebuilder:validation:Optional
	End []EndParameters `json:"end" tf:"end,omitempty"`
}

type ReplicationPolicyInitParameters struct {
	CheckpointRef *string `json:"checkpointRef,omitempty" tf:"checkpoint_ref,omitempty"`

	ReplicationMode *string `json:"replicationMode,omitempty" tf:"replication_mode,omitempty"`
}

type ReplicationPolicyObservation struct {
	CheckpointRef *string `json:"checkpointRef,omitempty" tf:"checkpoint_ref,omitempty"`

	ReplicationMode *string `json:"replicationMode,omitempty" tf:"replication_mode,omitempty"`
}

type ReplicationPolicyParameters struct {

	// +kubebuilder:validation:Optional
	CheckpointRef *string `json:"checkpointRef,omitempty" tf:"checkpoint_ref,omitempty"`

	// +kubebuilder:validation:Optional
	ReplicationMode *string `json:"replicationMode,omitempty" tf:"replication_mode,omitempty"`
}

type SitesInitParameters struct {
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// Uuid of the gslb object. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	ClusterUUID *string `json:"clusterUuid,omitempty" tf:"cluster_uuid,omitempty"`

	DNSVses []DNSVsesInitParameters `json:"dnsVses,omitempty" tf:"dns_vses,omitempty"`

	Enabled *string `json:"enabled,omitempty" tf:"enabled,omitempty"`

	HmProxies []HmProxiesInitParameters `json:"hmProxies,omitempty" tf:"hm_proxies,omitempty"`

	HmShardEnabled *string `json:"hmShardEnabled,omitempty" tf:"hm_shard_enabled,omitempty"`

	IPAddresses []IPAddressesInitParameters `json:"ipAddresses,omitempty" tf:"ip_addresses,omitempty"`

	Location []LocationInitParameters `json:"location,omitempty" tf:"location,omitempty"`

	MemberType *string `json:"memberType,omitempty" tf:"member_type,omitempty"`

	// Name for the gslb object. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	PasswordSecretRef v1.SecretKeySelector `json:"passwordSecretRef" tf:"-"`

	Port *string `json:"port,omitempty" tf:"port,omitempty"`

	Ratio *string `json:"ratio,omitempty" tf:"ratio,omitempty"`

	SuspendMode *string `json:"suspendMode,omitempty" tf:"suspend_mode,omitempty"`

	// Uuid of the gslb object. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`

	// Name for the gslb object. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type SitesObservation struct {
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// Uuid of the gslb object. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	ClusterUUID *string `json:"clusterUuid,omitempty" tf:"cluster_uuid,omitempty"`

	DNSVses []DNSVsesObservation `json:"dnsVses,omitempty" tf:"dns_vses,omitempty"`

	Enabled *string `json:"enabled,omitempty" tf:"enabled,omitempty"`

	HmProxies []HmProxiesObservation `json:"hmProxies,omitempty" tf:"hm_proxies,omitempty"`

	HmShardEnabled *string `json:"hmShardEnabled,omitempty" tf:"hm_shard_enabled,omitempty"`

	IPAddresses []IPAddressesObservation `json:"ipAddresses,omitempty" tf:"ip_addresses,omitempty"`

	Location []LocationObservation `json:"location,omitempty" tf:"location,omitempty"`

	MemberType *string `json:"memberType,omitempty" tf:"member_type,omitempty"`

	// Name for the gslb object. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	Port *string `json:"port,omitempty" tf:"port,omitempty"`

	Ratio *string `json:"ratio,omitempty" tf:"ratio,omitempty"`

	SuspendMode *string `json:"suspendMode,omitempty" tf:"suspend_mode,omitempty"`

	// Uuid of the gslb object. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`

	// Name for the gslb object. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type SitesParameters struct {

	// +kubebuilder:validation:Optional
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// Uuid of the gslb object. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	// +kubebuilder:validation:Optional
	ClusterUUID *string `json:"clusterUuid" tf:"cluster_uuid,omitempty"`

	// +kubebuilder:validation:Optional
	DNSVses []DNSVsesParameters `json:"dnsVses,omitempty" tf:"dns_vses,omitempty"`

	// +kubebuilder:validation:Optional
	Enabled *string `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// +kubebuilder:validation:Optional
	HmProxies []HmProxiesParameters `json:"hmProxies,omitempty" tf:"hm_proxies,omitempty"`

	// +kubebuilder:validation:Optional
	HmShardEnabled *string `json:"hmShardEnabled,omitempty" tf:"hm_shard_enabled,omitempty"`

	// +kubebuilder:validation:Optional
	IPAddresses []IPAddressesParameters `json:"ipAddresses,omitempty" tf:"ip_addresses,omitempty"`

	// +kubebuilder:validation:Optional
	Location []LocationParameters `json:"location,omitempty" tf:"location,omitempty"`

	// +kubebuilder:validation:Optional
	MemberType *string `json:"memberType,omitempty" tf:"member_type,omitempty"`

	// Name for the gslb object. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// +kubebuilder:validation:Optional
	PasswordSecretRef v1.SecretKeySelector `json:"passwordSecretRef" tf:"-"`

	// +kubebuilder:validation:Optional
	Port *string `json:"port,omitempty" tf:"port,omitempty"`

	// +kubebuilder:validation:Optional
	Ratio *string `json:"ratio,omitempty" tf:"ratio,omitempty"`

	// +kubebuilder:validation:Optional
	SuspendMode *string `json:"suspendMode,omitempty" tf:"suspend_mode,omitempty"`

	// Uuid of the gslb object. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	// +kubebuilder:validation:Optional
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`

	// Name for the gslb object. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	// +kubebuilder:validation:Optional
	Username *string `json:"username" tf:"username,omitempty"`
}

type ThirdPartySitesHmProxiesInitParameters struct {
	ProxyType *string `json:"proxyType,omitempty" tf:"proxy_type,omitempty"`

	// Uuid of the gslb object. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	SiteUUID *string `json:"siteUuid,omitempty" tf:"site_uuid,omitempty"`
}

type ThirdPartySitesHmProxiesObservation struct {
	ProxyType *string `json:"proxyType,omitempty" tf:"proxy_type,omitempty"`

	// Uuid of the gslb object. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	SiteUUID *string `json:"siteUuid,omitempty" tf:"site_uuid,omitempty"`
}

type ThirdPartySitesHmProxiesParameters struct {

	// +kubebuilder:validation:Optional
	ProxyType *string `json:"proxyType,omitempty" tf:"proxy_type,omitempty"`

	// Uuid of the gslb object. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	// +kubebuilder:validation:Optional
	SiteUUID *string `json:"siteUuid,omitempty" tf:"site_uuid,omitempty"`
}

type ThirdPartySitesInitParameters struct {

	// Uuid of the gslb object. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	ClusterUUID *string `json:"clusterUuid,omitempty" tf:"cluster_uuid,omitempty"`

	Enabled *string `json:"enabled,omitempty" tf:"enabled,omitempty"`

	HmProxies []ThirdPartySitesHmProxiesInitParameters `json:"hmProxies,omitempty" tf:"hm_proxies,omitempty"`

	Location []ThirdPartySitesLocationInitParameters `json:"location,omitempty" tf:"location,omitempty"`

	// Name for the gslb object. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	Ratio *string `json:"ratio,omitempty" tf:"ratio,omitempty"`

	// Uuid of the gslb object. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type ThirdPartySitesLocationInitParameters struct {
	Location []ThirdPartySitesLocationLocationInitParameters `json:"location,omitempty" tf:"location,omitempty"`

	Source *string `json:"source,omitempty" tf:"source,omitempty"`
}

type ThirdPartySitesLocationLocationInitParameters struct {
	Latitude *string `json:"latitude,omitempty" tf:"latitude,omitempty"`

	Longitude *string `json:"longitude,omitempty" tf:"longitude,omitempty"`

	// Name for the gslb object. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	Tag *string `json:"tag,omitempty" tf:"tag,omitempty"`
}

type ThirdPartySitesLocationLocationObservation struct {
	Latitude *string `json:"latitude,omitempty" tf:"latitude,omitempty"`

	Longitude *string `json:"longitude,omitempty" tf:"longitude,omitempty"`

	// Name for the gslb object. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	Tag *string `json:"tag,omitempty" tf:"tag,omitempty"`
}

type ThirdPartySitesLocationLocationParameters struct {

	// +kubebuilder:validation:Optional
	Latitude *string `json:"latitude,omitempty" tf:"latitude,omitempty"`

	// +kubebuilder:validation:Optional
	Longitude *string `json:"longitude,omitempty" tf:"longitude,omitempty"`

	// Name for the gslb object. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// +kubebuilder:validation:Optional
	Tag *string `json:"tag,omitempty" tf:"tag,omitempty"`
}

type ThirdPartySitesLocationObservation struct {
	Location []ThirdPartySitesLocationLocationObservation `json:"location,omitempty" tf:"location,omitempty"`

	Source *string `json:"source,omitempty" tf:"source,omitempty"`
}

type ThirdPartySitesLocationParameters struct {

	// +kubebuilder:validation:Optional
	Location []ThirdPartySitesLocationLocationParameters `json:"location,omitempty" tf:"location,omitempty"`

	// +kubebuilder:validation:Optional
	Source *string `json:"source" tf:"source,omitempty"`
}

type ThirdPartySitesObservation struct {

	// Uuid of the gslb object. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	ClusterUUID *string `json:"clusterUuid,omitempty" tf:"cluster_uuid,omitempty"`

	Enabled *string `json:"enabled,omitempty" tf:"enabled,omitempty"`

	HmProxies []ThirdPartySitesHmProxiesObservation `json:"hmProxies,omitempty" tf:"hm_proxies,omitempty"`

	Location []ThirdPartySitesLocationObservation `json:"location,omitempty" tf:"location,omitempty"`

	// Name for the gslb object. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	Ratio *string `json:"ratio,omitempty" tf:"ratio,omitempty"`

	// Uuid of the gslb object. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type ThirdPartySitesParameters struct {

	// Uuid of the gslb object. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	// +kubebuilder:validation:Optional
	ClusterUUID *string `json:"clusterUuid,omitempty" tf:"cluster_uuid,omitempty"`

	// +kubebuilder:validation:Optional
	Enabled *string `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// +kubebuilder:validation:Optional
	HmProxies []ThirdPartySitesHmProxiesParameters `json:"hmProxies,omitempty" tf:"hm_proxies,omitempty"`

	// +kubebuilder:validation:Optional
	Location []ThirdPartySitesLocationParameters `json:"location,omitempty" tf:"location,omitempty"`

	// Name for the gslb object. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// +kubebuilder:validation:Optional
	Ratio *string `json:"ratio,omitempty" tf:"ratio,omitempty"`

	// Uuid of the gslb object. Allowed in enterprise edition with any value, essentials, basic, enterprise with cloud services edition.
	// +kubebuilder:validation:Optional
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

// GSLBSpec defines the desired state of GSLB
type GSLBSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     GSLBParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider GSLBInitParameters `json:"initProvider,omitempty"`
}

// GSLBStatus defines the observed state of GSLB.
type GSLBStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        GSLBObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// GSLB is the Schema for the GSLBs API. Creates and manages Avi Gslb.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,avi}
type GSLB struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.leaderClusterUuid) || (has(self.initProvider) && has(self.initProvider.leaderClusterUuid))",message="spec.forProvider.leaderClusterUuid is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.sites) || (has(self.initProvider) && has(self.initProvider.sites))",message="spec.forProvider.sites is a required parameter"
	Spec   GSLBSpec   `json:"spec"`
	Status GSLBStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// GSLBList contains a list of GSLBs
type GSLBList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GSLB `json:"items"`
}

// Repository type metadata.
var (
	GSLB_Kind             = "GSLB"
	GSLB_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: GSLB_Kind}.String()
	GSLB_KindAPIVersion   = GSLB_Kind + "." + CRDGroupVersion.String()
	GSLB_GroupVersionKind = CRDGroupVersion.WithKind(GSLB_Kind)
)

func init() {
	SchemeBuilder.Register(&GSLB{}, &GSLBList{})
}
