apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    {{- include "provider-avi.labels" . | nindent 4 }}
type: {{ .Values.secret.type }}
stringData:
  credentials: |
    {
      "avi_username": {{ .Values.secret.username | quote }},
      "avi_tenant": {{ .Values.secret.tenant | quote }},
      "avi_password": {{ .Values.secret.password | quote }},
      "avi_controller": {{ .Values.secret.controller | quote }},
      "avi_version": {{ .Values.secret.version | quote }}
    }